version: 0.0
os: linux
files:
  - source: /webdem
    destination: /var/www/html/webdem
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_perm
      timeout: 300
      runas: root

